format = """
$username\
$hostname\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$julia\
$lua\
$python\
$rlang\
$rust\
$conda\
$memory_usage\
$env_var\
$custom\
$cmd_duration\
$line_break\
$jobs\
$status\
$shell\
$character"""
